[package]
name = "guwupher"
version = "0.1.0"
authors = ["n0body"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mime_guess = "2.0.3"